### ISSUE TITLE
Suggestions for pycoQC

### ISSUE THREAD

**Issue by monahanj** [a-slide/pycoQC#34]
Just tested pycoQC, here are a few thoughts:

I like the interactive plots but the labels on two of the plots ended up being cluttered, "Distribution of read length” and "Output over experiment time”.
(The Distribution of read length was cluttered because the narrow distribution for the poly(A) run, would probably not be an issue in most cases)

I think you should include an option to generate a new, filtered sequencing_summary.txt file.
I ended up generating these when I was analysing the poly(A) data.

Also it would make more sense if the parameters for —verbose_level were 2,1,0 (0 = silent).

**Comment by a-slide** [comment]
Hi Jack,
Thanks for the suggestions.

Regarding the legend cluttering, I know but since the plot are dynamically resized it is not really possible to check for the space between legend items. There are 2 ways around though. The first is to zoom in and the second is to hide legend items by clicking on them in the legend on the left.

The option to generate a new file is definitely something I should do. See #15

You last point makes sense. I will do it.

Thanks

**Comment by a-slide** [comment]
verbose_level change implemented in dev branch
