### ISSUE TITLE
Possible new functionality

### ISSUE THREAD

**Issue by TheChymist** [a-slide/pycoQC#5]
A useful addition would be to show cumulative yield over time.  This could also report how long into the run 1/4, 1/2, 3/4 of the output was generated.

Another possible addition would be to allow temporal ordering of multiple sequencing runs within an experiment. When a sequencing run is stopped or crashes and then is restarted the runID changes. Currently the analyses that output yield or quality over-time put these multiple runs together when they should (ideally) be consecutive. I don't think it is possible to tell solely from the sequence_summary.txt what the order of the runs was, but maybe the user could specify the order of the runIDs?

**Comment by a-slide** [comment]
Thanks, Good idea. for the cumulative output.

For the temporal ordering I think that the run_ids in the file are actually ordered by start time. It would make sense. I will be easy to check as would expect to have a decreasing yield over time. I will leave the possibility to the user to indicate the order of the reads anyway.

**Comment by a-slide** [comment]
Thanks. Good idea for the cumulative output and the output milestones.

For the temporal ordering I think that the run IDs in the file are actually ordered by start time. It would make sense and will be easy to check as we expect to have a decreasing yield over time. I will leave the possibility to the user to indicate the order of the run IDs anyway.

**Comment by a-slide** [comment]
All the plotting functions have been updated and now includes the requested functionalities, except the  1/4, 1/2, 3/4 that was a bit of a pain to implement. 

For the temporal order you were right, there is no way to be sure based on the Sequencing summary file only. However it looks like it is ordered for Albacore 2.0+. Let me know if you see the same thing. Otherwise you can indicate the order at initialisation.
