### ISSUE TITLE
Add filename to report

### ISSUE THREAD

**Issue by colindaven** [a-slide/pycoQC#85]
Timely and nice looking program and output - thanks!

**Is your feature request related to a problem? Please describe.**
Have multiple files open in browser and difficult to port with the metadata. A full path to filename would be helpful to discern output files.

**Describe the solution you'd like**
Simple request - please add a file name or better full file path to the top of the report (if not already done in dev or more recent version)

**Describe alternatives you've considered**

**Additional context**

**Comment by a-slide** [comment]
Hi Colin,
That's a good suggestion. It used to be the case but then we introduced the possibility to use multiple summary files as input and it became awkward. I guess we could just list the filenames if one is to use several. I will implement this feature in the next release. In the meantime you can use the option  `--report_title` to customize the html report title with a sample name.

Thanks

**Comment by a-slide** [comment]
Hi @colindaven,
I added the functionality in the new version of pycoQC. It is atthe bottom of the report though, because if one uses many summary files instead of a single one, this could be annoying.
I also update the '--report_title' option so that it replaces completely the default top title "pycoQC Report".

**Comment by colindaven** [comment]
Thanks @a-slide , I'll be sure to check it out after my next run completes.
