### ISSUE TITLE
exporting plotly tables from report to csv

### ISSUE THREAD

**Issue by inijman** [a-slide/pycoQC#86]
We often keep the data from the Run summary by barcode but since recent versions we cannot copy-paste it anymore and export is only as PNG.

Can  you allow the export to csv options from the plotly tables?

**Comment by a-slide** [comment]
Hi @inijman,
I will have a look, but I believe this is due to the plotly graphing library, and unfortunately I have no control over it.
Did you realise that pycoQC can also generate a json text file with most of the information from the summary file ? It is easy to parse and to convert the bits you are interested in CSV.

**Comment by inijman** [comment]
Thanks. I believe the plotly package allows the function to export as csv (https://community.plot.ly/t/allowing-users-to-download-csv-on-click/5550).

I did work on the JSON files but 2 modules throw json structure errors which I have not been able to figure out yet.

**Comment by a-slide** [comment]
The link you sent is for Dask not the basic plotly graphing library, which is more limited.
I just pushed a new version of pycoQC with a better formatted JSON report including extra information. This is where you should get the information you need from.
Let me know if you can parse it without issues.

**Comment by a-slide** [comment]
I will close this issue. Don't hesitate to reopen one if you still have problems with the JSON file
