### ISSUE TITLE
Combining several sequencing_summary.txt files

### ISSUE THREAD

**Issue by sulheim** [a-slide/pycoQC#9]
My sequencing was divided into two runs, and I therefore have two summary-files. I tried to combine them by just copy-pasting them together, but pycoQC doesn't count the reads from the second run. Is there a simple way to solve this?

**Comment by a-slide** [comment]
Hi there,
If the 2 files have the same column header (which should be the case as you probably used the same run parameters in Albacore) it should work in theory. The only other reason I see that could interfere is if you didn't discard the column header of the second file when concatenating you 2 files.
Otherwise if it is not the case, you could also basecall your 2 runs together directly in Albacore but running it from the root folder containing both runs

**Comment by sulheim** [comment]
Sorry, but I messed it up myself, because tabs were converted to spaces during copy-paste in sublime. So the second part wasn't read properly by pd.read_csv, and thus this part of the dataframe was removed by df.dropna

**Comment by a-slide** [comment]
No worries.
Happy to see that pycoQC is spreading in the community.
I could add an option to give multiple summary files at initialization though.
